<p class="intro">Browse your favorite West Coast Swing video by <br />
<br />
<?php foreach ($this->categories as $category): ?>
    <a href="<?php echo $this->url(array('category' => $category->category), 'tagcategory') ?>"><?php echo $category->category ?></a>,
<?php endforeach; ?><br />
<br />
or <a href="/video/list">see all videos</a></p>
<br />
<br />

<div class="lfloat">
  <h3>Recently added/tagged</h3>
  <ul>
    <?php echo $this->partialLoop('index/_videoentry.phtml', $this->latest) ?>
  </ul>
</div>

<br style="clear:both" />
<br />
<br />

<p>You may help us improve this website by submitting a new WCS video clip for tagging</p>
<form method="post" action="<?php echo $this->url(array('controller' => 'video', 'action' => 'submit')) ?>">
  <input type="text" name="url" id="url" value="paste a youtube video url..." size="32" />
  <input type="submit" value="...and submit it!" />
</form>


<script type="text/javascript">
    submittext = 'paste a youtube video url...';
    
    $('#url').click(function(event){
        if (event.target.value == submittext) {
            event.target.value = '';
        }
    });

    $('#url').blur(function(event){
        if (event.target.value == '') {
            event.target.value = submittext;
        }
    });
</script>
