<div class="span-20 append-4">
  <div class="box intro">
  <p>Browse your favorite West Coast Swing video by<br />
	<?php foreach ($this->categories as $category): ?>
	    <a href="<?php echo $this->url(array('category' => $category->category), 'tagcategory') ?>"><?php echo $category->category ?></a>,
	<?php endforeach; ?>
	or <a href="/video/list">see all videos</a></p>
</div>


<div class="span-24 prepend-top append-bottom">
  <h3>Recently added/tagged</h3>
  <ul>
	    <?php echo $this->partialLoop('index/_videoentry.phtml', $this->latest) ?>
  </ul>
</div>

<div class="span-24">
You may help us improve this website by submitting a new WCS video clip for tagging<br />
<form method="post" action="<?php echo $this->url(array('controller' => 'video', 'action' => 'submit')) ?>">
  <input type="text" name="url" id="url" value="paste a youtube video url..." size="32" />
  <input type="submit" value="...and submit it!" />
</form>
</div>

<script type="text/javascript">
    submittext = 'paste a youtube video url...';
    
    $('#url').click(function(event){
        if (event.target.value == submittext) {
            event.target.value = '';
        }
    });

    $('#url').blur(function(event){
        if (event.target.value == '') {
            event.target.value = submittext;
        }
    });
</script>
