<?php echo $this->doctype() ?>
<html>
<head>
  <?php echo $this->headTitle() ?>
  <?php echo $this->headLink()->appendStylesheet('/css/main.css'); ?>
  <?php echo $this->headScript()->appendFile('/js/jquery-1.3.2.min.js')?>
</head>
<body>
<div id="container">
  <h1><a href="/">SubYT</a></h1>
  <?php echo $this->layout()->content ?>
  <p id="footer">&copy; 2009 <a href="http://danceric.net">Danceric</a></p>
</div>
</body>
</html>